openapi: 3.0.0
info:
  title: runlog-api-v1
  version: '1.0'
  license:
    name: MIT
  contact:
    name: Yoshiki Shino
    url: 'https://github.com/yoshikipom'
    email: yoshiki.shino.tech@gmail.com
servers:
  - url: 'http://localhost:8080'
paths:
  /records:
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Record'
              examples:
                example-1:
                  value:
                    - date: '2020-06-01'
                      distance: 10
                      memo: test memo
                    - date: '2020-06-02'
                      distance: 10
                      memo: test memo
      operationId: get-records
      parameters:
        - schema:
            type: string
          in: query
          name: month
          description: YYYY-MM
    parameters: []
    put:
      summary: ''
      operationId: put-records
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Record'
  '/records/{date}':
    parameters:
      - schema:
          type: string
          format: date
          deprecated: false
        name: date
        in: path
        description: ''
        required: true
    delete:
      summary: ''
      operationId: delete-records-date
      description: ''
      responses:
        '204':
          description: No Content
    get:
      summary: ''
      operationId: get-records-date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Record'
              examples:
                example-1:
                  value:
                    date: '2020-06-01'
                    distance: 10
                    memo: test memo
  /monthRecords:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MonthRecord'
      operationId: get-monthRecords
      parameters:
        - schema:
            type: integer
          in: query
          name: year
          required: true
components:
  schemas:
    Record:
      title: Record
      type: object
      x-examples:
        example-1:
          date: '2020-06-01'
          distance: 10
          memo: test memo
      description: ''
      properties:
        date:
          type: string
          description: YYYY-MM-DD
        distance:
          type: number
        memo:
          type: string
      required:
        - date
        - distance
        - memo
    MonthRecord:
      title: MonthRecord
      type: object
      x-examples:
        example-1:
          sum: 100
          month: 1
      properties:
        sum:
          type: number
        month:
          type: integer
      required:
        - sum
